### ISSUE TITLE
Virtual Terminal not relaying input keystrokes to output stream

### ISSUE THREAD

**Issue by listba** [jline/jline3#1074]
Virtual Terminals no longer seem to be working correctly for me from version 3.25.1 onward. I looked through the [code changes](https://github.com/jline/jline3/compare/jline-parent-3.25.0...jline-parent-3.25.1) but nothing really stood out to me as the root cause.

I'm using JLine with a virtual terminal to run a websocket based repl via xtermjs. From 3.25.1 onward the Jline terminal no longer appears to be relaying the input back out to the output stream. It also seems to be unable to display the prompt prefix from `LineReader.readLine(prompt)`.

Ive coded up a small demo app (in scala) that demonstrates how I am using JLine. 

demo app: https://gist.github.com/listba/8597d857b7af43303999dc19496bea77

Running this with JLine `3.25.1+` you can see that input keystrokes are never relayed back to the terminal. The prompt display shows `>....` instead of `lang>`.
The line reader still works and you can tell that the terminal is receiving the input characters (eg type a few characters and press enter and the line reader will print out the captured input text). But the users interactions themselves are not getting drawn.

if you drop the version down to `3.25.0` and run it again everything works like you would expect it to. 

Any help on this would be appreciated.

**Comment by gnodet** [comment]
It works if you use `org.jline:jline-reader`, whatever version you use, including the latest one.
It seems to point to native libraries. I think Scala embeds a version of JLine, and given a single native library can be loaded by JVM, any more recent JLine version may break if trying to load a native library.
Note that 3.25.0 is broken in that regard at it does not embed the native libraries (see https://github.com/jline/jline3/commit/7ff2fbc5430f3a96069f3352847c730ac15f5c79).  Using a `jline-reader` dependency instead of `jline` is a nice workaround, as using the smaller jars, no native library will be loaded at all, as they won't be in the classpath.
Another workaround is to avoid loading the  JLine providers  by using the following code:
```
      val terminal = TerminalBuilder.builder()
          .jna(false).jansi(false).jni(false).ffm(false)
          .system(false).streams(jIn, jOut).build()
```
This allows using any recent version of `jline` bundle.

**Comment by listba** [comment]
Ah ok perfect thank you switching to `jline-reader` fixed it in my full project as well. Thanks!
