### ISSUE TITLE
Completion candiates should be provided by Completer not LineReader

### ISSUE THREAD

**Issue by facingBackwards** [jline/jline3#147]
The current implementation of `LineReaderImpl` runs its own filtering on candidates and can ignore completions from the completer.

This is counter intuitive and I feel it would be better for the reader to trust the completer to return valid completions and then handle them and offer the choice to the user. It could also be beneficial to move the handling out of the reader and into a `CompletionHandler` (with a `DefaultHandler` providing the current behaviour) similar to how JLine2 handled completions.

#### Example
Given a completer that provides camelCase completions (similar to Eclipse)
``` python
>>> obj.gF # completions should be getFoo, getFooBar, getFizz, getFBuzz
```
I have a completer that returns these completions but they are ignored because they don't match the hardcoded matchers in LineReaderImpl (startsWith, contains or typoMatch).

I have partially worked around this problem by setting ERRORS to an arbitrarily high number to allow 'typos'. However, this fails when one of the matches does start with the completion eg with the example above, completing on `getFB` should return `getFooBar` and `getFBuzz` but because one starts with the text being completed, the typoMatcher is never used and only `getFBuzz` is returned.

If this is an acceptable idea, I'll open a PR with the change.

**Comment by gnodet** [comment]
I disagree. I think the completers should return the full list of candidates, while matchers are responsible for the filtering.  The reasons is that if you want to add camel case completion, you'd have to rewrite all your completers.  Unless you assume that some completers return a partial list, and others return a filtered list (as this was the case in jline2), but I find that it conflates two different things.
The problem is that the matchers are not extensible.
Would you mind working on a PR to make matchers extensible ? a camel case matcher would be a good test as you pointed out.

**Comment by facingBackwards** [comment]
Ok, that's a fair argument. I had converted a jline2 completer that did its own filtering. I will change it to return all completions and work on a PR for a CompletionMatcher/Handler.
