### ISSUE TITLE
Improve terminal encoding support

### ISSUE THREAD

**Issue by gnodet** [jline/jline3#174]
The encoding used on the `input` and `output` streams are not very clearly determined.
The API should be made more explicit about those and offer a uniform layer on all platforms.

See #168 for some discussion around that.

**Comment by gnodet** [comment]
The encoding used should at least be available on the `Terminal` interface.

**Comment by Minecrell** [comment]
I considered three different solutions (2 and 3 are kind of similar):

1. As you mentioned above, expose the encoding used for the input and output stream. A potential problem here is that if we set Windows to e.g. `UTF-8` by default, this could break existing applications because most of them read using the default system encoding. You commonly read/write from the console like `new PrintStream(terminal.output(), true);` and in these cases the default system encoding is used.

On Windows, we can emulate all charsets in the `WriterOutputStream`, so we could also make the charset configurable. The advantage is that we could default it to default system encoding and avoid breaking any existing applications (because they need to opt-in if they can ensure everything writes using the correct charset).

2. Use `TerminalBuilder.encoding(String)` to set the encoding for the Windows input/output streams. The advantage is that this API exists already, but the "charset emulation" only works on Windows so the encoding set there would also affect the other platforms (and potentially in a bad way if a wrong encoding is used).

3. Expose methods on `Terminal` to create a `InputStream`/`OutputStream` using a specific charset. I think it's a bit overkill, but we could add a method like

    ```java
    // Should be either @Nullable or throw an exception if unsupported
    OutputStream createOutputStream(Charset charset);
    ```

    On all platforms except Windows this would return null/throw an exception unless the default system encoding is used.

---

2 and 3 might be overkill considering this is only supported on Windows so it might be best if we do 1 instead.

When we choose `UTF-8` as encoding for the Windows output/input stream, ASCII input/output should still work even when read with the system default encoding (e.g. `windows-1252`) because it is encoded in the same way. The only difference is that you get garbage if you write Unicode characters instead of `???`.

**Comment by gnodet** [comment]
I'd go for #1 but with using the encoding from the TerminalBuilder if set, and defaulting to the default system encoding otherwise (as it should be the case for posix system terminals too iirc).
I'd still expose the encoding on the Terminal api (read-only):
```
    Charset encoding();
```

**Comment by Minecrell** [comment]
That's pretty much 2. actually. The only problem with that solution is that there isn't a way to set the encoding to the `TerminalBuilder` only for the Windows terminal. As you mention, the default system encoding is usually the right one for posix system terminals, so I wouldn't want to force it to UTF-8 if that isn't supported anyway.

When I do:

```java
Terminal terminal = TerminalBuilder.builder().system(true).encoding("UTF-8").build();
PrintStream out = new PrintStream(terminal.output(), true, terminal.encoding().name());
out.write("Hello world!");
```

JLine now uses `UTF-8` on all platforms, even if they may not support it. I'd need to detect Windows manually but that isn't nice either.

**Comment by gnodet** [comment]
Right, the problem is slightly different on posix and windows, because for posix systems, the encoding is more an input value that the application needs to set to behave correctly, whereas on windows, we could set it to pretty much anything, since the Input/OutputStreams are built on top of the Reader/Writer.
The default value could be null in the `TerminalBuilder` to allow each `Terminal` implementation to choose its default.  This could allow having the default encoding on posix and UTF-8 on windows by default.

**Comment by Minecrell** [comment]
Yes, think making it nullable is a good idea. That way you could still set `TerminalBuilder.encoding(Charset.defaultCharset())` to restore the old behavior.

**Comment by Minecrell** [comment]
@gnodet Are you going to make the changes we discussed here or should I prepare a PR for that?

**Comment by gnodet** [comment]
Feel free to work on it :-)
