### ISSUE TITLE
completion sort order doesn't seem to respect the `.compareTo` fn on the Candidates

### ISSUE THREAD

**Issue by bhauman** [jline/jline3#205]
First of all, terrific work on Jline3.

I'm currently making an advanced readline interface to the Clojure REPL and Jline3 is really amazing.

The only snag that I've run into is my blind hope that the `.compareTo` method on Candidate would be respected. I really would like to use `length` as a primary sort attribute.

Is there a way around this without subclassing `LineReaderImpl`?

**Comment by gnodet** [comment]
I agree that would make sense, but the problem is that we need to be able to sort case insensitively to obey the `Option.CASE_INSENSITIVE` flag.
A possible way to solve the problem would be to add a `sorting` field of type `String` to the `Candidate` that would be used to sort the list of candidates.  
Worst case, I can add a `getCandidateComparator` method so that subclassing would be easier.

**Comment by bhauman** [comment]
Yes, a hook for the comparator would be nice. I was having a difficult time tracking it down.

I wont pretend to understand your design scope as I have very little experience programming terminal interfaces.  It does "seem to me" that a  [length alpha] sorting of prefix matches makes a lot of sense as it appears "closer" to the input. 

i.e. given the prefix `def` then `defn` is closer than `default` by virtue of being similar in length.

But again, I'm sure I'm simply not taking time to consider the other situations where the current behavior works better.
