### ISSUE TITLE
JLine 3.6.0 pause()/resume() spawns multiple pump readers if toggled quickly

### ISSUE THREAD

**Issue by cjohnstoninv** [jline/jline3#226]
If the pause() and resume() methods are toggled quick enough, the underlying thread for the pump reader never ends up closing and new thread is still spawned. The pause() method should instead block until truly paused. I'll submit a PR for this.

**Comment by gnodet** [comment]
I think your PR is not sufficient as another thread could do a resume while the first one is blocked during a call to pause and there would be a possible leak.
Could you have a look at https://github.com/gnodet/jline3/commit/5a64e45bda2d53a06d449f2a5f74c905bfa90f89 and see if this works for you ?

**Comment by cjohnstoninv** [comment]
Sure this would work and be thread safe. My thought at initial look was that these classes were not intended to be threadsafe to begin with. And that it would be a requirement of the callers of pause() / resume() to ensure thread safety. On further review, the "compareAndSet" operation was making it thread safe to do. If maintaining thread safety of the Terminal implementations is the goal then we should merge in your change instead. While rare, I can think of cases an application would require multiple threads to handle the pause()/resume() methods.

**Comment by gnodet** [comment]
I'm not satisfied by your or mine PR yet.
Could you describe a bit more your use case please ? I understand the problem of spawning multiple threads and it should definitely be fixed. The problem is that `PosixPtyTerminal` and `ExternalTerminal` have blocking input streams, so they will block until a character is actually read and there's no way to interrupt the read.  In those cases, the `pause` call be simply avoid reading anymore characters.
So I'm not at east with blocking forever the `pause` call ...
I'm wondering about a different fix: `pause` would keep the current semantic, i.e. return immediately for forbids further reading more from the terminal.  However, if you call `pause` then `resume` very quickly, then the thread may not be killed / recreated, depending if the thread has died yet or not.  
In addition, if that's actually needed, we could add a `pause(boolean join)` method that may actually block.
Thoughts ?

**Comment by gnodet** [comment]
Let me know if this last PR works for you.  The benefit is that it should be fully backward compatible (code and semantic).  If you need to actually wait for the threads to die, you'll have to cast the `Terminal` to `AbstractTerminal`.  It will be added to the `Terminal` interface in 3.7.0 (see #231).

**Comment by cjohnstoninv** [comment]
I wouldn't mind a `pause(boolean join)` method to maintain backward compatibility. To explain my use case a little more, I have written a shell like application that has set of "commands" it can run. These commands support a basic set of pipe / redirect operations to other commands. One of the commands I have is "system" which simply just executes whatever you pass it after system to a `ProcessBuilder` for a new process. 

How I found the bug of the quick toggle of `pause()` and `resume()` is that I was simply testing it by executing `system echo test` in my shell which subsequently executed `echo test` using `ProcessBuilder`. The fact that `echo test` executed so quickly it toggled the pause and resume. 

This didn't necessarily break anything in my shell as almost all commands would've run long enough to allow the pause to actually complete. For example when I ran the command `system bash -c "echo test"` I was not having the toggle issue (which really had me stumped for a while). But eventually after watching the active threads I realized what was occurring. Thanks so much for your help getting this fixed!
