### ISSUE TITLE
Support correct line wrapping in org.jline.utils.Display

### ISSUE THREAD

**Issue by gnodet** [jline/jline3#25]
See https://github.com/jline/jline2/issues/256

**Comment by gnodet** [comment]
Display currently only supports being fed with trimmed lines, i.e. lines with a length of at most the width of the terminal.  So the user has to split the lines before giving them to Display.
The downside is that, on terminals that supports line wrapping (and when the user actually use wrapped lines), the line wrapping is lost when copy/pasting the terminal output to a text editor for example : the copied lines have newlines where lines are wrapped on the terminal.

This should be enhanced so that copy/pasting work better.

**Comment by gnodet** [comment]
Just a few quick questions:
  * is there any use case for having {{delayLineWrap=false}} ?
  * is the application now supposed to give to the {{Display}} class a list of lines that are not split yet, i.e. lines that can be longer and will be wrapped, so that {{Display}} can differentiate between a line that needs wrapping and a line that has been adjusted to the terminal width (a right prompt for example)

**Comment by gnodet** [comment]
Can you merge the commit https://github.com/gnodet/jline3/commit/8e921519dbc5fc228ab8776effe616d19c2ca5f2 which fixes right prompt support in your PR ?

When the delay-line-wrap option is set to true, I have some weird behaviours when a soft new line is added in the middle of a multi-line editing...  Could you double-check ?

**Comment by PerBothner** [comment]
[I didn't get any email notification about your comments, and I didn't see them until now. Sorry about the delayed response.]

First: "is there any use case for having {{delayLineWrap=false}}"

The issue is what happens after you type (say) 80 characters (of prompt+input) on an 80-column terminal: where do you want the cursor to be?  Should it be at the right margin of the full line, or the left margin of the empty next line?  There are pluses and minuses either way.

Emacs has explicit wrap indicators, and so does DomTerm.  In that case, showing the cursor at the margin is not a problem.  However, some terminal emulators don't show this situation clearly.  Gnome Terminal hides the cursor when at the right margin. Xterm highlights the last character, just as if the cursor were one column to the left.

GNU readline solves this by moving the cursor to a fresh line in case of a 80-character line.  There are (at least) two problems with this:

1. acceptLine adds an extra newline, so you end up with a blank line, which is mildly annoying/ugly. It seems like this should be fixable at the acceptLine level, though I haven't figured what would need to be fixed.  Do you have any suggestions?

2. There are some anomalies with multi-line input.  For example a 160-character line followed by a 50-character line.  The former gets split as 3 lines, including a blank one.  This is confusing/ugly, especially in the context of a text editor, rather than just a repl.

Note that the master trunk has the same issues - with some extra bugs.  (The cursor sometimes gets positions before the prompt.)

Note with either mode (and in Emacs) if you have (say) a 81-column line with the cursor at position 80, then we put the cursor at the start of the second line, rather than at the right margin of the first line.  The issue is what to do when the line length exactly matches the available column width.  Emacs does not create extra blank lines if you have 80-column lines.

**Comment by PerBothner** [comment]
_"is the application now supposed to give to the {{Display}} class a list of lines that are not split yet, i.e. lines that can be longer and will be wrapped, so that {{Display}} can differentiate between a line that needs wrapping and a line that has been adjusted to the terminal width (a right prompt for example)"_

No - as I gather you figured out, based on your patch.  Display gets a a list of lines that *have* been split, but any newlines are preserved as the final character of the split lines.

**Comment by PerBothner** [comment]
I'm hoping my new patches have fixed the "weird behaviours when a soft new line is added in the middle of a multi-line editing".  Could you check?

**Comment by gnodet** [comment]
I already had the needed fixes for nano, so I merged your PR and closed the issue.
