### ISSUE TITLE
Provide a better auto-suggestion mechanism

### ISSUE THREAD

**Issue by gnodet** [jline/jline3#254]
![image](https://2.bp.blogspot.com/-X8raHCDc4JA/WqJHiYWXOnI/AAAAAAAAFH4/FMjWQfDOJgkcOzi8angMnEa51aSSYjy2gCLcBGAs/s1600/image1.gif)

**Comment by acodervic** [comment]
How did you do it with jline3? Do you have the source code? thanks!

**Comment by mattirn** [comment]
@acodervic, see [console:org/jline/example/Console.java](https://github.com/jline/jline3/blob/master/console/src/test/java/org/jline/example/Console.java). Found a bug (NPE) that I have fixed in latest the snapshot.
 
![image](https://user-images.githubusercontent.com/6079480/169708230-b836b2cc-f4d8-44cc-9822-076bb5bb87b1.png)
