### ISSUE TITLE
Dumb terminal when piping input to console app disallows ANSI formatting

### ISSUE THREAD

**Issue by bdw429s** [jline/jline3#299]
When I pipe input to CommandBox like so:

```
echo myCommand | box.exe
```
Then the JLine uses a dumb terminal which prevents the commands from using any ANSI formatting, even though I may be running inside of a terminal that is fully capable of 256 colors, etc.  It is correct that JLIne uses a dumb terminal in this situation?

**Comment by gnodet** [comment]
No, I think the problem comes from the fact that JLine does not support having 2 different terminal types for the input and the output.  In your case, the input is not a real terminal, but the output is.
The actual problem is located at:
  https://github.com/jline/jline3/blob/master/terminal/src/main/java/org/jline/utils/AttributedCharSequence.java#L46-L48

**Comment by mattirn** [comment]
JLine `TerminalBuilder` will create dumb-color terminal if output stream is connected to terminal and the enviroment variable `TERM` is set. Does not work an EXEC based terminals -you need to have JNA or Jansi lib in your classpath.
