### ISSUE TITLE
How to use jline3 connect to a standard telnet server?

### ISSUE THREAD

**Issue by hengyunabc** [jline/jline3#318]
Hi, I tried the following examples

* Telnet server: https://github.com/jline/jline3/blob/master/remote-telnet/src/main/java/org/jline/builtins/telnet/Telnet.java 
* Example: https://github.com/jline/jline3/blob/master/builtins/src/test/java/org/jline/example/Example.java

But I did not find an example of using jline to connect to the standard telnet server. Is there any relevant information?

**Comment by gnodet** [comment]
You're right, there's no example of connecting to a telnet server.  Mostly because anyone can use a native telnet client to connect to the server started in jline.

JLine won't be of much help on the client side : it's only role would be to catch terminal resize events and forward them.  The setup can mostly be done by using environment variables.
The telnet library embedded in jline is mostly for the server side, if you're fancy, feel free to have a closer look and see if the client side can be implemented.

**Comment by hengyunabc** [comment]
@gnodet  Thanks, I totally agree with you. But now many users do not have telnet under windows 10 by default; there are some docker images without telnet. 
So I want to write a pure java telnet client.

**Comment by gnodet** [comment]
Sounds good.  I can guide you on the JLine part of the client, but you need to find a good telnet java client library to use.  Apache Commons-Net could be a good candidate as it seems to support the required options, though I've never used it.

**Comment by hengyunabc** [comment]
Thanks again. 
Actually, I tried Apache Commons-Net demo, it seems that I need to handle `tab`/`up`/`down` keyboard event, then send to the telnet server. 
I tried to debug `StringsCompleter` in jline3, I haven't found out how jline3 register these keyboard hooks. Could you provide relevant information?

**Comment by gnodet** [comment]
JLine can't be used on the client side.  It's meant to be used on the server side of the telnet connection.

**Comment by hengyunabc** [comment]
Thanks. I finished a demo, using jline and commons-net: https://github.com/hengyunabc/java-telnet-client-demo
