### ISSUE TITLE
curses curses

### ISSUE THREAD

**Issue by bamcgill** [jline/jline3#469]
I see a curses src in jline3 but no examples of using it.
Is it possible to create "popups" with curses in jline3?  I'm thinking of things like code insight etc.
We're about to port to this now and trying to work out how everything will hang together.

**Comment by gnodet** [comment]
I experimented a bit with a curses window manager 2 years ago.  The results are available at:
  https://github.com/jline/jline3/tree/curses/curses/src/main/java/org/jline/curses
I've rebased the branch on master so that it's easier to try.
It's far from being finished however, but if you're willing to spend some time and provide patches, we can certainly improve it.
There's an example of its usage in the branch:
  https://github.com/jline/jline3/blob/curses/curses/src/test/java/org/jline/curses/CursesTest.java

**Comment by apatrida** [comment]
@gnodet does this handle resize correctly?  If the terminal isn't rendering newlines you change the size it will skew the old text.  You can clear on resize to repaint it, which works in full screen.  Is that the expected model for aligning the terminal lines correctly on resize?

**Comment by gnodet** [comment]
> @gnodet does this handle resize correctly? If the terminal isn't rendering newlines you change the size it will skew the old text. You can clear on resize to repaint it, which works in full screen. Is that the expected model for aligning the terminal lines correctly on resize?

This is supposed to be handled by https://github.com/jline/jline3/blob/curses/curses/src/main/java/org/jline/curses/impl/GUIImpl.java#L159 but there may be some bugs, I haven't tried since quite some time.
