### ISSUE TITLE
Navigating grouped candidates using arrow keys is broken

### ISSUE THREAD

**Issue by mattirn** [jline/jline3#580]
Navigating grouped command candidates is broken. There are also other problems if the grouped candidates do not fit to the terminal display.

Example: From the initial position BYTES pressing once the left arrow key selected candidate moves to toHexString

![menu_1](https://user-images.githubusercontent.com/6079480/94293719-03dccf00-ff5f-11ea-9177-418a78426a3f.png) 

![menu-2-left-arrow](https://user-images.githubusercontent.com/6079480/94293724-063f2900-ff5f-11ea-834f-d2ecb9b0101e.png)

**Comment by bdw429s** [comment]
This was the wrong solution to just remove functionality instead of fixing it.  Please restore the missing and useful functionality of candidate grouping.  

See: https://github.com/jline/jline3/issues/613

And if JLine follows semantic versioning, it was also incorrect to introduce a breaking change into a minor release.
