### ISSUE TITLE
Does Jline Support select-option based control on terminal

### ISSUE THREAD

**Issue by vsaji** [jline/jline3#592]
Sorry, if this topic has been discussed here earlier. 

I am working on picocli+jline project whereby I have a requirement to show a list of values and ask the user to select one of them and use that value further. 

Something similar you see it in this gif. This is supported in nodejs based CLI app, but I am wondering if this can be achieved in JLine.
https://miro.medium.com/max/640/1*rY1AAM3lhu7e67PuzW0s_Q.gif

Kindly advice.

**Comment by mattirn** [comment]
No, JLine does not have built-in support for select-option.

**Comment by mattirn** [comment]
@vsaji, I have added in [Example](https://github.com/jline/jline3/blob/master/builtins/src/test/java/org/jline/example/Example.java) an implementation of select-option based control. Take a look if it could be useful in your project.

**Comment by PashaTurok** [comment]
@mattirn I am also looking for a select option for jline. I've checked your example.  Thank you for sharing your solution. However, it is difficult to use in real situation because jumping from one screen to another is not good. I think it is necessary to modify it at something like [this](https://github.com/cyrilwanner/cli-select#readme )
