### ISSUE TITLE
problem with display history when use mouse wheel 

### ISSUE THREAD

**Issue by toanvan** [jline/jline3#601]
I use jline 3.17.1 version. I saw a problem related to display history. When we use mouse wheel, it has a problem 
 - **Display history command instead of implement status scroll bar terminal**

I use **Tera Term** terminal and it was this issue. But I use **PuTTY** or **Bitvise** terminal there was no problem.
In case **Tera Term** if I open file TERATERM.INI (in installed Tera Term) and set paramter TranslateWheelToCursor and change: TranslateWheelToCursor=off, then there was no problem.

Please help me this issue which no need to configure file in **Tera Term**.

Thank you

**Comment by mattirn** [comment]
I think this a problem of Tera Term rather than JLine.

As a work around you could try build your terminal as
```
Terminal terminal = TerminalBuilder.builder().build();
terminal.puts(org.jline.utils.InfoCmp.Capability.exit_ca_mode);
```
If possible you should execute the last statement only when using Tera Term

**Comment by toanvan** [comment]
I tried add 
`Terminal terminal = TerminalBuilder.builder().build();
terminal.puts(org.jline.utils.InfoCmp.Capability.exit_ca_mode);`

But It's still problem. So I think it's problem of Tera Tearm

**Comment by gnodet** [comment]
@toanvan I think this is an expected behaviour. I imagine that the `TranslateWheelToCursor=on` means that the wheel scroll action will be translated to one of more  up/ down arrow events.  JLine interprets those as  the arrow keys and scroll the command in the history.  There's nothing JLine can do here, as it can only react to the events it receives.  The only way is to set `TranslateWheelToCursor=off`, I can't think about another workaround.
