### ISSUE TITLE
input text is overwritten

### ISSUE THREAD

**Issue by Fatonndev** [jline/jline3#666]
I searched all over Google and did not find how to fix it.
Code (send text):
```java
String result = ...
lineReader.callWidget(LineReader.CLEAR);
lineReader.getTerminal().writer().println(result);
lineReader.callWidget(LineReader.REDRAW_LINE);
lineReader.callWidget(LineReader.REDISPLAY);
```
Code (read text):
```java
while(true) {
    String line = lineReader.readLine("> ");
    Core.app.post(() -> handleCommandString(line));
}
```

![GIF 24 04 2021 15-47-31](https://user-images.githubusercontent.com/56699208/115959357-8852f880-a514-11eb-8327-00baed91c622.gif)

**Comment by mattirn** [comment]
This looks to me the same problem as reported in  #630 and resolved by pull request #649 (JLine 3.19.1)

**Comment by Fatonndev** [comment]
Hmm, okay... I changed my code and now there is no text at all...

Code (send text):
```java
try {
    PrintAboveWriter pw = new PrintAboveWriter(lineReader);
    pw.write(result.toCharArray());
    pw.flush();
} catch (Exception e) {
    e.printStackTrace();
}
```
![GIF 24 04 2021 19-06-02](https://user-images.githubusercontent.com/56699208/115965094-299b7800-a530-11eb-9ab1-a3cba7ef0f08.gif)

**Comment by mattirn** [comment]
It is not clear to me what is overwriting your current command line. I thought the lines like 
```
[04-24-2021 16:46:00  [I] Loading map...
```
are your application traces that are messing up your terminal display. If they are traces I think you should use `WriteAboveWriter` to print them.

Anyway I see you are using Windows terminal. You should add either `Jansi` or `JNA` jar to your classpath in order to get proper terminal, see [Jansi vs JNA](https://github.com/jline/jline3#jansi-vs-jna)

**Comment by Fatonndev** [comment]
My problem is solved, i installed `JNA`. `PrintAboveWriter` was not needed.
