### ISSUE TITLE
Simultaneous input and output?

### ISSUE THREAD

**Issue by gravityfox** [jline/jline3#75]
I'm trying to use JLine for a command interface of a headless application, however I'm having trouble figuring out how to set it up so that if something get's outputted to the console while I'm typing, the output doesn't interleave.

If my console looks like:
```
Hello
> mycommand
```

And then I print "World!"

I want it to look like this:
```
Hello
World!
> mycommand
```

But it ends up looking like this:
```
Hello
> mycommandWorld!
```

Surely there is a way to accomplish what I want.

I know that normally the line reader blocks, but for this application, console output should be constantly updated.

**Comment by gnodet** [comment]
This looks a bit similar to #53.

Instead of simply printing "World!", you need to do the [following](https://github.com/jline/jline3/blob/b14eb5ecb498eb0d09191a6ca4511e19a953f736/src/test/java/org/jline/example/Example.java#L201-L205):
```
   reader.getTerminal().puts(Capability.carriage_return);
   reader.getTerminal().writer().println("World!");
   reader.callWidget(LineReader.REDRAW_LINE);
   reader.callWidget(LineReader.REDISPLAY);
   reader.getTerminal().writer().flush();
```

However, this is not a perfect solution, as it will only work if the user is editing a single line.  If the input is multiline, the "World!" line won't appear.  I'll provide a new widget to fix the behavior.

**Comment by gnodet** [comment]
With the upcoming jline 3.2, you'll have a cleaner fix which will work with multiline input:
```
   reader.callWidget(LineReader.CLEAR);
   reader.getTerminal().writer().println("World!");
   reader.callWidget(LineReader.REDRAW_LINE);
   reader.callWidget(LineReader.REDISPLAY);
   reader.getTerminal().writer().flush();
```

**Comment by gravityfox** [comment]
Hold on. If you're already grabbing the system out stream, why can't this be more built in?

**Comment by gnodet** [comment]
Feel free to reopen if needed.
