### ISSUE TITLE
How to bind the shortcut key ctrl+1

### ISSUE THREAD

**Issue by acodervic** [jline/jline3#783]
How to bind the shortcut key ctrl+1?

i can bind ctrl+s  ,but i cant bind   ctrl+1.

            map.bind(new Reference(LineReader.UP_LINE_OR_SEARCH), KeyMap.ctrl('1'));

please help me , thanks!

**Comment by acodervic** [comment]
i try to 
```java
            int a = 1;
            char c = (char) a;
            map.bind(new Reference(LineReader.UP_LINE_OR_SEARCH), KeyMap.ctrl(c));
```

but is doesn't work.

**Comment by mattirn** [comment]
I think it is not possible to bind `<ctrl>-1` because your terminal does not detect `<ctrl>-1`. In general the `<ctrl>-<number>` produces the different key codes, see for example [cannot-map-ctrl-number](https://vi.stackexchange.com/questions/19358/cannot-map-ctrl-number-except-6-or).

Note that in JLine you cannot bind `<ctrl>-4` (`<ctrl>-\`), see #441.

**Comment by acodervic** [comment]
> I think it is not possible to bind `<ctrl>-1` because your terminal does not detect `<ctrl>-1`. In general the `<ctrl>-<number>` produces the different key codes, see for example [cannot-map-ctrl-number](https://vi.stackexchange.com/questions/19358/cannot-map-ctrl-number-except-6-or).
> 
> Note that in JLine you cannot bind `<ctrl>-\` (`<ctrl>-4`), see #441.
thanks
