### ISSUE TITLE
Autocompletion with candidates having space in them.

### ISSUE THREAD

**Issue by amolb1** [jline/jline3#792]
I am using Jline 3.21.0 and trying to run a simple test with reference from https://github.com/jline/jline3/blob/master/reader/src/test/java/org/jline/reader/completer/StringsCompleterTest.java

Below is a  modified testcase with candidates having spaces in them. After giving input as "foo b" without quote and pressing tab I am expecting output to be "foo bar" but I get output as "foo foo bar".

Is this expected behavior ? How can I fix it ? Thanks in advance.

   ```
     DefaultParser dp = (DefaultParser) reader.getParser();
     dp.setEscapeChars(new char[]{});
     reader.setVariable(LineReader.ERRORS, 0);
     reader.setParser(dp);
     reader.setCompleter(new StringsCompleter("foo bar", "foo foo", "foo shoo"));

     assertBuffer("foo bar ", new TestBuffer("foo b").tab()); // fails actual output is "foo foo bar"
```

**Comment by mattirn** [comment]
That is expected behavior.

DefaultParser parses command line parameters as space separated strings. If your parameter have spaces then you have to quote your parameter (or escape the spaces in your parameter). In your example:

```
assertBuffer("foo 'foo bar' ", new TestBuffer("foo b").tab());
```
 i.e. in above case your command line first parameter is `foo` and you are completing the second parameter `b` since your candidates have only one candidate that have char 'b' it will be completed as `'foo bar'`. If you had set DefaultParser escapeChars as `dp.setEscapeChars(new char[] { '\\' })` then the second parameter would be completed as `foo\ bar`. 

You can also add the quote yourself when writing command line:
```
assertBuffer("'foo bar' ", new TestBuffer("'foo b").tab());
```

**Comment by amolb1** [comment]
Thanks @mattirn for quick response.

**Comment by mattirn** [comment]
@amolb1 you are welcome, I just updated my answer above ....

**Comment by amolb1** [comment]
Just FYI @mattirn, overriding below method had solved my particular problem. 
DefaultParser parser = new DefaultParser() {
				@Override
				public boolean isDelimiterChar(CharSequence charSeqBuffer, int position) {
					boolean isWhiteSpaceChar = Character.isWhitespace(charSeqBuffer.charAt(position));
					if (isWhiteSpaceChar && position + 1 < charSeqBuffer.length()
							&& !Character.isWhitespace(charSeqBuffer.charAt(position + 1))) {
						return false;
					}
					return isWhiteSpaceChar;
				}

			};
