### ISSUE TITLE
Hierarchical commands easy setup (feature request)

### ISSUE THREAD

**Issue by adibacco** [jline/jline3#90]
Setting up a Completer is very flexible but sometimes it generates a long piece of code that is also quite difficult to read. It would be really nice to have a Completer that can be setup with a tree-like structure whose nodes contain a List of Candidates. This approach doesn't cover all possible scenarios but it is very useful in most cases. Consider a Cisco-like CLI for example.

I think the same approach is used in https://github.com/dparrish/libcli

**Comment by gnodet** [comment]
I see the use case.  I haven't run into yet though, mostly because most of the commands I define take options, so that a strict hierarchical completion does not really help.
What could be interesting also is a slightly more complicate completer that you could configure using a syntax such as:
```
(C1 | C2 | C3)* C4? C5+
```
which would mean : 0 or more occurrences of c1 or c2 or c3, eventually followed by c4, followed by one or more c5, where c[1-9] would be keys into a `Map<String, Completer>`.

**Comment by gnodet** [comment]
See https://github.com/jline/jline3/blob/104a5eb754cde677cf16033422df697e2c6914ab/builtins/src/test/java/org/jline/example/Example.java#L163-L180

**Comment by adibacco** [comment]
Really neat way to specify a tree-like commands structure. Just for people that would need "hint" for certain values to insert I created a class like this:


```
package org.jline.reader;

import java.util.Objects;

public class Hint extends Candidate {

	public Hint(String suggestion) {
		super("", suggestion, null, "", null, null, false);
	}
	public Hint(String suggestion, String description) {
		super("", suggestion, null, description, null, null, false);
	}
}
```
and then I modified **Completer.java** like this:

```

                    if (res instanceof Candidate) {
                        candidates.add((Candidate) res);
                    **} else if (res instanceof Hint) {
                        candidates.add((Hint) res);**
                    } else if (res instanceof String) {

```
