### ISSUE TITLE
Ctrl-C behaviour not consistent on Linux

### ISSUE THREAD

**Issue by lucdono77** [jline/jline3#913]
Hello,
I am experiencing different behaviour with the CTRL-C handling. On Windows (regardless if it is a system terminal or not), I can catch the **UserInterruptedException** when CTRL-C is hit.

However, on Linux, this only happens with the system terminal.

Indeed, running the example _builtins/src/test/java/org/jline/example/Example.java_ with, for instance the params **color +system**, CTRL-C correctly clears the line:

![image](https://github.com/jline/jline3/assets/150752877/f4151e4d-302b-4060-b2eb-39df38a4fb31)

On the other hand, running the same example with **color -system**, CTRL-C  no exception is thrown and the process is killed:
![image](https://github.com/jline/jline3/assets/150752877/933d636d-e002-40ef-8279-b43d7698a9f3)

Is there some settings I need to add/handle when a not-system terminal is used or this is actually a bug?
Any help is very appreciated.

Best Regards,
Luca

**Comment by gnodet** [comment]
A non system terminal is disconnected from the terminal you're running in.  The point is to behave like a telnet / ssh session.  In such cases, the signals need to be sent to JLine through the input stream using the characters configured on the terminal attributes (VINTR in this very case).
However, if you run the example in a real terminal, to mimic the behaviour, you'd have to trap the system signal using sun.misc.Signal and then feed it to the input stream connected to the terminal (which in the example is System.in, so that's a bit difficult to achieve).
Anyway, non system terminals are for very specific purposes, i.e. handle a terminal which is remotely connected.

**Comment by lucdono77** [comment]
Indeed, that's my use case: I am running the non system terminal in a telnet session (server side), while a system terminal is handling the client side of the communication (to implement my own telnet client).
Server and clients can run on the very same process or on 2 separate processes: in both cases CTRL-C terminates the process on Linux (I am using 3.24.0), but on Windows it seems the **UserInterruptedException** is raised instead (at least on my last check using 3.23.0 on Windows).
When I connect to the server via the Linux telnet command, it seems CTRL-C has no effect at all.

I suspect in both cases, as for your advice, I should programmatically handle the signal on the client side.

Anyway, thanks a lot for you clarification, I'll try your solution.

**Comment by gnodet** [comment]
> I suspect in both cases, as for your advice, I should programmatically handle the signal on the client side.

Yes, if a JVM is running on the client, it needs to be configured in a way that you can trap the signals and send the corresponding characters to the stream.
See https://github.com/jline/jline3/blob/e82b526acadaa037459fb7651588910c98c28873/remote-ssh/src/main/java/org/jline/builtins/ssh/Ssh.java#L259-L290, where the JLine's system terminal on the client is used to send the signals to the remote terminal through ssh.

**Comment by lucdono77** [comment]
Thanks for it! That's very helpful.

**Comment by gnodet** [comment]
Reopen if needed.
