### ISSUE TITLE
Remote SSH module

### ISSUE THREAD

**Issue by PhBastiani** [jline/jline3#925]
Reading the SSH module code, I discovered that when building the terminal you used attributes from the SSH environment.
If I understand correctly by doing...
 <code>
Attributes attributes = new Attributes(); 
... 
TerminalBuilder.builder().attributes(attributes); 
</code>
...you are overriding the attributes defined by default in ExternalTerminal: is this the goal ?

I say this because, the ptymode map  seems often empty (eg  when starting a basic ssh session with sshd 2.11.0); and therefore, we lose the default capabilities of the terminal.

Is this an error or a misunderstanding on my part ?

Best Wishes,
Philippe

**Comment by gnodet** [comment]
> Reading the SSH module code, I discovered that when building the terminal you used attributes from the SSH environment. If I understand correctly by doing... ` Attributes attributes = new Attributes(); ... TerminalBuilder.builder().attributes(attributes); ` ...you are overriding the attributes defined by default in ExternalTerminal: is this the goal ?
> 
> I say this because, the ptymode map seems often empty (eg when starting a basic ssh session with sshd 2.11.0); and therefore, we lose the default capabilities of the terminal.
> 
> Is this an error or a misunderstanding on my part ?
> 
> Best Wishes, Philippe

The full attributes properties are supposed to be sent by the client.
In the demo, this is done [here](https://github.com/jline/jline3/blob/32d2af1417d0f96b1a7d588188f1c37a4fb979d7/remote-ssh/src/main/java/org/jline/builtins/ssh/Ssh.java#L204-L248).
The goal is to send the exact attributes from the client side terminal to the remote side, so that the behaviour will be correct.

**Comment by gnodet** [comment]
Closing this issue.  Come back if needed.
